In [1]:
# Importe as bibliotecas necessárias para este projeto
import numpy as np
import pandas as pd
import envelopment as env

In [2]:
# Import as tabelas saneamento
# Executar somente uma fez. Depois que a tabele tenha sido escalonada import a tabela do final
df_saneamento = pd.read_csv("dados_limpos_saneamento.csv")

In [3]:
df_saneamento.head()

Cód Município Tp Empresa Nat Jurídica  Pop Total  Perdas Fat  Perdas Dist  \
0         355030    Pública     SEMAPubl   12038175       24.69        36.69   
1         330455    Pública     SEMAPubl    6498837       52.41        25.36   
2         530010    Pública     SEMAPubl    2977216       24.71        35.21   
3         292740    Pública     SEMAPubl    2938092       44.19        53.07   
4         230440    Pública     SEMAPubl    2609716       26.66        42.64   

   Tarifa méd  Ext rede água  Ext rede esgotos  Empregados      ...       UF  \
0        3.66       21262.00          17101.64        4897      ...       SP   
1        4.16       10891.20           4864.51        3105      ...       RJ   
2        4.74        8534.49           6377.11        2517      ...       DF   
3        3.66        5358.67           3506.06        1447      ...       BA   
4        2.99        4112.66           2442.27        5910      ...       CE   

         Empresa At Água At Esgoto  Novas Lig Água  Novas Lig Esgoto  \
0         SABESP   100.0     97.00           77.37             57.45   
1  CEDAE / FABZO    99.0     85.16           58.78             17.29   
2          CAESB    99.1     85.23           68.48             12.41   
3         EMBASA    90.6     78.77           18.01             14.92   
4         CAGECE    83.3     49.68            5.61              7.77   

   Ev Perdas Fat  Ev Perdas Dist  Esg Tratado  Investimento  
0           0.00            0.00        61.96       9113.98  
1           0.84            3.90        44.51       1922.68  
2           0.88            0.00        84.42        878.80  
3          25.82            0.00       100.00        544.32  
4          14.36            6.78        53.19        806.14  

[5 rows x 22 columns]

In [4]:
df_saneamento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 22 columns):
Cód Município          95 non-null int64
Tp Empresa             95 non-null object
Nat Jurídica           95 non-null object
Pop Total              95 non-null int64
Perdas Fat             95 non-null float64
Perdas Dist            95 non-null float64
Tarifa méd             95 non-null float64
Ext rede água          95 non-null float64
Ext rede esgotos       95 non-null float64
Empregados             95 non-null int64
Código do município    95 non-null int64
Município              95 non-null object
UF                     95 non-null object
Empresa                95 non-null object
At Água                95 non-null float64
At Esgoto              95 non-null float64
Novas Lig Água         95 non-null float64
Novas Lig Esgoto       95 non-null float64
Ev Perdas Fat          95 non-null float64
Ev Perdas Dist         95 non-null float64
Esg Tratado            95 non-null float64
Investi

In [5]:
df_saneamento.shape

(95, 22)

In [6]:
inputs = np.array(df_saneamento[['Perdas Fat',
                                 'Perdas Dist',
                                 'Tarifa méd',
                                 'Investimento',
                                 'Ext rede água',
                                 'Ext rede esgotos',
                                 'Empregados']])

In [7]:
outputs = np.array(df_saneamento[['At Água',
                                  'At Esgoto',
                                  'Esg Tratado',
                                  'Novas Lig Água',
                                  'Novas Lig Esgoto',
                                  'Ev Perdas Fat',
                                  'Ev Perdas Dist']])

In [8]:
names = []
names += df_saneamento['Município'].tolist()

In [9]:
dea = env.DEA(inputs, outputs)

In [10]:
dea.name_units(names)

Às vezes, o algoritmo de otimização SLSQP para cedo dando o erro:

Derivativo direcional positivo para pesquisa de linhas (modo de saída 8)
Nesse caso, você pode tentar seguir as coisas:

Se você tiver os sinalizadores de compilador nativo -ffast-math -march = ativos (veja acima), tente desativá-los.
Use uma malha mais fina na área do local da turbina. Os erros numéricos de representar as turbinas podem estar dominando o problema.
Use uma tolerância de otimização mais flexível, passando o parâmetro tol para maximizar a função.
Se você estiver otimizando apenas para o atrito da turbina e não usar o parâmetro automatic_scaling (o que você deve neste caso específico), talvez seja necessário dimensionar o problema manualmente. Isto é feito passando um argumento de escala para maximizar, e. maximizar (rf, escala = 1e-3). Escolha o valor da escala de forma que o primeiro gradiente seja da ordem de 1.

https://github.com/OpenTidalFarm/OpenTidalFarm/wiki/Optimisation-stops-with-Exit-mode-8

Às vezes, o algoritmo de otimização SLSQP para cedo dando o erro:

Derivativo direcional positivo para pesquisa de linhas (modo de saída 8)
Nesse caso, você pode tentar seguir as coisas:

Se você tiver os sinalizadores de compilador nativo -ffast-math -march = ativos (veja acima), tente desativá-los.
Use uma malha mais fina na área do local da turbina. Os erros numéricos de representar as turbinas podem estar dominando o problema.
Use uma tolerância de otimização mais flexível, passando o parâmetro tol para maximizar a função.
Se você estiver otimizando apenas para o atrito da turbina e não usar o parâmetro automatic_scaling (o que você deve neste caso específico), talvez seja necessário dimensionar o problema manualmente. Isto é feito passando um argumento de escala para maximizar, e. maximizar (rf, escala = 1e-3). Escolha o valor da escala de forma que o primeiro gradiente seja da ordem de 1.

In [11]:
dea.fit()

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.6539001471808397
            Iterations: 13
            Function evaluations: 1454
            Gradient evaluations: 13
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.664332149055561
            Iterations: 9
            Function evaluations: 1010
            Gradient evaluations: 9
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.5817424238248001
            Iterations: 10
            Function evaluations: 1112
            Gradient evaluations: 10
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.9729814244227729
            Iterations: 10
            Function evaluations: 1006
            Gradient evaluations: 9
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.5674431385486255
            Iterations: 9
            Func

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.7203446884069998
            Iterations: 9
            Function evaluations: 1000
            Gradient evaluations: 9
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.7803557022776626
            Iterations: 8
            Function evaluations: 888
            Gradient evaluations: 8
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 1.0000000557405586
            Iterations: 8
            Function evaluations: 893
            Gradient evaluations: 8
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.6199608459937404
            Iterations: 9
            Function evaluations: 1000
            Gradient evaluations: 9
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.9106702572438432
            Iterations: 13
            Function 

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.8532373334572667
            Iterations: 8
            Function evaluations: 889
            Gradient evaluations: 8
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 1.0000000132738867
            Iterations: 5
            Function evaluations: 555
            Gradient evaluations: 5
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 1.0000000001632414
            Iterations: 7
            Function evaluations: 777
            Gradient evaluations: 7
Positive directional derivative for linesearch    (Exit mode 8)
            Current function value: -54.259436564198985
            Iterations: 6
            Function evaluations: 222
            Gradient evaluations: 2
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 1.0000010867749898
            Iterations: 9
            Fu

In [12]:
df_saneamento[df_saneamento.index == 69]

Cód Município Tp Empresa Nat Jurídica  Pop Total  Perdas Fat  Perdas Dist  \
69         351620    Pública     SEMAPubl     344704       12.51        25.85   

    Tarifa méd  Ext rede água  Ext rede esgotos  Empregados      ...       UF  \
69        2.62        1201.47           1149.21        2820      ...       SP   

   Empresa At Água At Esgoto  Novas Lig Água  Novas Lig Esgoto  Ev Perdas Fat  \
69  SABESP   100.0     100.0           98.52             100.0           2.12   

    Ev Perdas Dist  Esg Tratado  Investimento  
69            2.14        98.03        325.99  

[1 rows x 22 columns]

In [13]:
dea.efficiency

array([[  0.65390015],
       [  0.66433215],
       [  0.58174242],
       [  0.97298142],
       [  0.56744314],
       [  0.67337197],
       [  0.55669029],
       [  0.87364411],
       [  1.        ],
       [  0.77081406],
       [  0.67816078],
       [  1.        ],
       [  0.7836767 ],
       [  0.65621203],
       [  0.65256452],
       [  0.67327911],
       [  0.70885422],
       [  0.61034446],
       [  0.86937312],
       [  0.89110362],
       [  0.75287554],
       [  0.79048759],
       [  0.76462867],
       [  1.        ],
       [  0.88781114],
       [  1.00000002],
       [  0.95484396],
       [  0.89951632],
       [ 11.05490217],
       [  0.56591821],
       [  1.        ],
       [  0.6716365 ],
       [  0.88893923],
       [  0.63394417],
       [  0.7072887 ],
       [  0.78663717],
       [  0.75334225],
       [  0.73089301],
       [  0.60452417],
       [  1.00000891],
       [  0.72034469],
       [  0.7803557 ],
       [  1.00000006],
       [  0

In [14]:
eficiencia = dea.efficiency

In [15]:
eficiencia

array([[  0.65390015],
       [  0.66433215],
       [  0.58174242],
       [  0.97298142],
       [  0.56744314],
       [  0.67337197],
       [  0.55669029],
       [  0.87364411],
       [  1.        ],
       [  0.77081406],
       [  0.67816078],
       [  1.        ],
       [  0.7836767 ],
       [  0.65621203],
       [  0.65256452],
       [  0.67327911],
       [  0.70885422],
       [  0.61034446],
       [  0.86937312],
       [  0.89110362],
       [  0.75287554],
       [  0.79048759],
       [  0.76462867],
       [  1.        ],
       [  0.88781114],
       [  1.00000002],
       [  0.95484396],
       [  0.89951632],
       [ 11.05490217],
       [  0.56591821],
       [  1.        ],
       [  0.6716365 ],
       [  0.88893923],
       [  0.63394417],
       [  0.7072887 ],
       [  0.78663717],
       [  0.75334225],
       [  0.73089301],
       [  0.60452417],
       [  1.00000891],
       [  0.72034469],
       [  0.7803557 ],
       [  1.00000006],
       [  0

# dados fornecidos

In [16]:
dea.inputs

array([[ 2.469000e+01,  3.669000e+01,  3.660000e+00,  9.113980e+03,
         2.126200e+04,  1.710164e+04,  4.897000e+03],
       [ 5.241000e+01,  2.536000e+01,  4.160000e+00,  1.922680e+03,
         1.089120e+04,  4.864510e+03,  3.105000e+03],
       [ 2.471000e+01,  3.521000e+01,  4.740000e+00,  8.788000e+02,
         8.534490e+03,  6.377110e+03,  2.517000e+03],
       [ 4.419000e+01,  5.307000e+01,  3.660000e+00,  5.443200e+02,
         5.358670e+03,  3.506060e+03,  1.447000e+03],
       [ 2.666000e+01,  4.264000e+01,  2.990000e+00,  8.061400e+02,
         4.112660e+03,  2.442270e+03,  5.910000e+03],
       [ 3.603000e+01,  3.736000e+01,  4.290000e+00,  1.061720e+03,
         6.837510e+03,  4.393250e+03,  1.802000e+03],
       [ 6.576000e+01,  4.415000e+01,  5.310000e+00,  2.937100e+02,
         3.712810e+03,  5.244100e+02,  8.100000e+03],
       [ 2.890000e+01,  3.946000e+01,  3.700000e+00,  6.937600e+02,
         7.327520e+03,  6.131340e+03,  2.693000e+03],
       [ 5.270000e+01,  

In [17]:
dea.outputs

array([[1.0000e+02, 9.7000e+01, 6.1960e+01, 7.7370e+01, 5.7450e+01,
        0.0000e+00, 0.0000e+00],
       [9.9000e+01, 8.5160e+01, 4.4510e+01, 5.8780e+01, 1.7290e+01,
        8.4000e-01, 3.9000e+00],
       [9.9100e+01, 8.5230e+01, 8.4420e+01, 6.8480e+01, 1.2410e+01,
        8.8000e-01, 0.0000e+00],
       [9.0600e+01, 7.8770e+01, 1.0000e+02, 1.8010e+01, 1.4920e+01,
        2.5820e+01, 0.0000e+00],
       [8.3300e+01, 4.9680e+01, 5.3190e+01, 5.6100e+00, 7.7700e+00,
        1.4360e+01, 6.7800e+00],
       [9.5000e+01, 9.2490e+01, 7.2160e+01, 5.2300e+00, 2.6310e+01,
        0.0000e+00, 1.5500e+00],
       [8.8200e+01, 1.0230e+01, 2.3800e+01, 2.3200e+01, 3.5000e-01,
        1.7500e+00, 4.4200e+00],
       [1.0000e+02, 9.9990e+01, 9.2930e+01, 1.0000e+02, 1.0000e+02,
        0.0000e+00, 0.0000e+00],
       [8.3800e+01, 4.1670e+01, 7.3750e+01, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00],
       [1.0000e+02, 8.9990e+01, 5.3540e+01, 1.0000e+02, 1.9840e+01,
        0.0000e+00, 0.0

 # parameters
- n = número de entidades (observações)
- m = número de entradas (variáveis, características)
- r = número de saídas

In [18]:
# número de entidades (observações)
dea.n

95

In [19]:
# número de imputs (variáveis, características)
dea.m

7

In [20]:
# número de outputs
dea.r

7

In [21]:
outputs.shape[1]

7

In [22]:
outputs.shape

(95, 7)

In [23]:
novo_df2 = pd.DataFrame(names, columns=['Mun'])

In [24]:
novo_df2['eficiencia_DEA'] = dea.efficiency

In [25]:
novo_df2[novo_df2['eficiencia_DEA']>2]

Mun  eficiencia_DEA
28  Uberlândia       11.054902

In [26]:
df_saneamento.head()

Cód Município Tp Empresa Nat Jurídica  Pop Total  Perdas Fat  Perdas Dist  \
0         355030    Pública     SEMAPubl   12038175       24.69        36.69   
1         330455    Pública     SEMAPubl    6498837       52.41        25.36   
2         530010    Pública     SEMAPubl    2977216       24.71        35.21   
3         292740    Pública     SEMAPubl    2938092       44.19        53.07   
4         230440    Pública     SEMAPubl    2609716       26.66        42.64   

   Tarifa méd  Ext rede água  Ext rede esgotos  Empregados      ...       UF  \
0        3.66       21262.00          17101.64        4897      ...       SP   
1        4.16       10891.20           4864.51        3105      ...       RJ   
2        4.74        8534.49           6377.11        2517      ...       DF   
3        3.66        5358.67           3506.06        1447      ...       BA   
4        2.99        4112.66           2442.27        5910      ...       CE   

         Empresa At Água At Esgoto  Novas Lig Água  Novas Lig Esgoto  \
0         SABESP   100.0     97.00           77.37             57.45   
1  CEDAE / FABZO    99.0     85.16           58.78             17.29   
2          CAESB    99.1     85.23           68.48             12.41   
3         EMBASA    90.6     78.77           18.01             14.92   
4         CAGECE    83.3     49.68            5.61              7.77   

   Ev Perdas Fat  Ev Perdas Dist  Esg Tratado  Investimento  
0           0.00            0.00        61.96       9113.98  
1           0.84            3.90        44.51       1922.68  
2           0.88            0.00        84.42        878.80  
3          25.82            0.00       100.00        544.32  
4          14.36            6.78        53.19        806.14  

[5 rows x 22 columns]

In [27]:
df_saneamento['Eficiencia_DEA'] = pd.DataFrame(dea.efficiency * 100).round({0:2})

In [28]:
#df_saneamento['Eficiencia_DEA'] = dea.efficiency

In [29]:
df_saneamento['Eficiencia_DEA'].dtypes

dtype('float64')

In [30]:
df_saneamento[df_saneamento['Município'] == 'Macapá']

Cód Município Tp Empresa Nat Jurídica  Pop Total  Perdas Fat  Perdas Dist  \
47         160030    Pública     SEMAPubl     465495       63.06        66.25   

    Tarifa méd  Ext rede água  Ext rede esgotos  Empregados       ...        \
47        2.66         707.86             89.29        2250       ...         

    Empresa At Água At Esgoto Novas Lig Água  Novas Lig Esgoto  Ev Perdas Fat  \
47    CAESA    39.4      9.04            3.6              3.42           2.68   

    Ev Perdas Dist  Esg Tratado  Investimento  Eficiencia_DEA  
47            4.18        16.87         52.86           90.83  

[1 rows x 23 columns]

In [31]:
df_saneamento[['Município', 'Eficiencia_DEA']][df_saneamento['Eficiencia_DEA']>100]

Município  Eficiencia_DEA
28     Uberlândia         1105.49
94  Várzea Grande          117.59

In [32]:
df_saneamento[df_saneamento['Eficiencia_DEA']>100]

Cód Município Tp Empresa Nat Jurídica  Pop Total  Perdas Fat  Perdas Dist  \
28         317020    Pública    Autarquia     669672        20.2         25.2   
94         510840    Pública    Autarquia     271339        60.7         60.7   

    Tarifa méd  Ext rede água  Ext rede esgotos  Empregados       ...        \
28        1.69         3206.0            2571.0        8370       ...         
94        1.86         1163.1             136.5        2850       ...         

      Empresa At Água At Esgoto Novas Lig Água  Novas Lig Esgoto  \
28       DMAE   100.0    100.00         100.00             37.21   
94  MUNICÍPIO    97.0     29.73          19.46              1.24   

    Ev Perdas Fat  Ev Perdas Dist  Esg Tratado  Investimento  Eficiencia_DEA  
28          11.63            1.33        76.44        266.05         1105.49  
94           2.41            3.12        35.39          0.00          117.59  

[2 rows x 23 columns]

In [33]:
#Criando novo dataset com os dados limpos
df_saneamento.to_csv('dados_limpos_saneamentoDEA.csv', index=False)